# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 06:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coral_code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coral_code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyBookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provision_code', models.CharField(max_length=255)),
                ('hotel_code', models.CharField(max_length=50)),
                ('coral_booking_code', models.CharField(max_length=255)),
                ('room_type', models.CharField(max_length=50)),
                ('room_description', models.CharField(max_length=255)),
                ('pax_count', models.IntegerField()),
                ('pax_names', models.TextField()),
                ('price', models.FloatField()),
                ('email', models.EmailField(max_length=254)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=100, unique=True)),
                ('used_flag', models.BooleanField(default=False)),
                ('creation_time', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
