# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_mybookings_book_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybookings',
            name='book_time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
